/**
 * 英雄别名/昵称索引。
 * 用于搜索框：用户输入"亚索"应匹配到"疾风剑豪"(Yasuo)。
 * key = DDragon 英雄 id（英文），value = 该英雄的所有可搜索称呼列表。
 * 数据来源：DDragon zh_CN 的 name(称号) + title(本名) + id(英文) + 玩家常用昵称。
 */
export const CHAMPION_ALIASES: Record<string, string[]> = {
  Aatrox: ['剑魔', '亚托克斯', '暗裔剑魔', 'aatrox'],
  Ahri: ['阿狸', '九尾妖狐', '狐狸', 'ahri'],
  Akali: ['阿卡丽', 'akali'],
  Akshan: ['阿克尚', 'akshan'],
  Alistar: ['牛头', '阿利斯塔', 'alistar', '牛头酋长'],
  Amumu: ['阿木木', '木木', 'amumu'],
  Anivia: ['艾尼维亚', '冰鸟', 'anivia'],
  Annie: ['安妮', '火女', 'annie'],
  Aphelios: ['厄斐琉斯', '月男', 'afk', 'aphelios'],
  Ashe: ['艾希', '寒冰', 'ashe'],
  AurelionSol: ['奥瑞利安索尔', '龙王', '铸星龙王', 'aurelionsol'],
  Aurora: ['奥罗拉', 'aurora'],
  Azir: ['阿兹尔', '沙皇', '黄鸡', 'azir'],
  Bard: ['巴德', '星界游神', 'bard'],
  BelVeth: ['卑尔维斯', '贝蕾亚', 'belyth', 'belveth', '虚空女皇'],
  Blitzcrank: ['布里茨', '机器人', 'blitzcrank'],
  Brand: ['布兰德', '火男', 'brand'],
  Braum: ['布隆', 'braum'],
  Briar: ['布莉尔', 'briar'],
  Caitlyn: ['凯特琳', '女警', 'caitlyn'],
  Camille: ['卡蜜尔', '青钢影', 'camille'],
  Cassiopeia: ['卡西奥佩娅', '蛇女', 'cassiopeia'],
  Chogath: ['科加斯', '大虫子', 'chogath', 'cho'],
  Corki: ['库奇', '飞机', 'corki'],
  Darius: ['德莱厄斯', '诺手', 'darius'],
  Diana: ['黛安娜', '月女', 'diana'],
  Draven: ['德莱文', 'draven'],
  DrMundo: ['蒙多', '蒙多医生', 'drmundo'],
  Ekko: ['艾克', 'ekko'],
  Elise: ['伊莉丝', '蜘蛛', 'elise'],
  Evelynn: ['伊芙琳', '寡妇', 'evelynn'],
  Ezreal: ['伊泽瑞尔', 'ez', 'ezreal'],
  Fiddlesticks: ['费德提克', '稻草人', 'fiddlesticks', 'fiddle'],
  Fiora: ['菲奥娜', '剑姬', 'fiora'],
  Fizz: ['菲兹', '小鱼人', 'fizz'],
  Galio: ['加里奥', 'galio'],
  Gangplank: ['普朗克', '船长', 'gangplank', 'gp'],
  Garen: ['盖伦', 'garen', '德玛'],
  Gnar: ['纳尔', 'gnar'],
  Gragas: ['古拉加斯', '酒桶', 'gragas'],
  Graves: ['格雷福斯', '男枪', 'graves'],
  Gwen: ['格温', 'gwen'],
  Hecarim: ['赫卡里姆', '人马', 'hecarim'],
  Heimerdinger: ['黑默丁格', '大头', 'heimerdinger', 'heimer'],
  Hwei: ['辉', 'hwei'],
  Illaoi: ['俄洛伊', 'illaoi'],
  Irelia: ['艾瑞莉娅', '刀妹', 'irelia'],
  Ivern: ['艾翁', '翠神', 'ivern'],
  Janna: ['迦娜', '风女', 'janna'],
  JarvanIV: ['嘉文四世', '皇子', 'jarvaniv', 'jarvan', 'j4'],
  Jax: ['贾克斯', 'jax', '武器大师'],
  Jayce: ['杰斯', 'jayce'],
  Jhin: ['烬', 'jhin'],
  Jinx: ['金克丝', 'jinx', '暴走萝莉'],
  Kaisa: ['卡莎', 'kaisa', '卡莎'],
  Kalista: ['卡莉丝塔', '滑板鞋', 'kalista'],
  Karma: ['卡尔玛', 'karma'],
  Karthus: ['卡尔萨斯', '死歌', 'karthus'],
  Kassadin: ['卡萨丁', 'kassadin'],
  Katarina: ['卡特琳娜', '卡特', 'katarina', 'kata'],
  Kayle: ['凯尔', 'kayle'],
  Kayn: ['凯隐', 'kayn'],
  Kennen: ['凯南', 'kennen'],
  Khazix: ['卡兹克', '螳螂', 'khazix', 'kha'],
  Kindred: ['千珏', 'kindred'],
  Kled: ['克烈', 'kled'],
  KogMaw: ['克格莫', '大嘴', 'kogmaw', 'kog'],
  Leblanc: ['乐芙兰', '妖姬', 'leblanc', 'lb'],
  LeeSin: ['李青', '瞎子', '盲僧', 'leesin', 'lee'],
  Leona: ['蕾欧娜', '日女', 'leona'],
  Lillia: ['莉莉娅', 'lillia'],
  Lissandra: ['丽桑卓', '冰女', 'lissandra'],
  Lucian: ['卢锡安', '奥巴马', 'lucian'],
  Lulu: ['璐璐', 'lulu'],
  Lux: ['拉克丝', 'lux', '光辉'],
  Malphite: ['墨菲特', '石头人', 'malphite'],
  Malzahar: ['玛尔扎哈', '蚂蚱', 'malzahar'],
  Maokai: ['茂凯', '树精', 'maokai'],
  MasterYi: ['易', '易大师', '剑圣', 'masteryi', 'yi'],
  MissFortune: ['赏金', '厄运小姐', 'mf', 'missfortune', '女枪'],
  Wukong: ['孙悟空', '猴子', 'wukong', 'monkey'],
  Mordekaiser: ['莫德凯撒', '铁男', 'mordekaiser', 'morde'],
  Morgana: ['莫甘娜', 'morgana', '莫甘娜'],
  Naafiri: ['娜菲丽', 'naafiri'],
  Nami: ['娜美', 'nami'],
  Nasus: ['内瑟斯', '狗头', 'nasus'],
  Nautilus: ['诺提勒斯', '泰坦', 'nautilus', 'naut'],
  Neeko: ['妮蔻', 'neeko'],
  Nidalee: ['奈德丽', '豹女', 'nidalee'],
  Nilah: ['尼菈', 'nilah'],
  Nocturne: ['魔腾', '梦魇', 'nocturne', 'noc'],
  NunuWillump: ['努努', 'nunuwillump', 'nunu'],
  Olaf: ['奥拉夫', 'olaf', '狂战士'],
  Orianna: ['奥莉安娜', '发条', 'orianna'],
  Ornn: ['奥恩', 'ornn'],
  Pantheon: ['潘森', 'pantheon'],
  Poppy: ['波比', 'poppy'],
  Pyke: ['派克', 'pyke'],
  Qiyana: ['奇亚娜', 'qiyana'],
  Quinn: ['奎因', 'quinn'],
  Rakan: ['洛', 'rakan'],
  Rammus: ['拉莫斯', '龙龟', 'rammus'],
  RekSai: ['雷克塞', '挖掘机', 'reksai'],
  Rell: ['芮尔', 'rell'],
  RenataGlas: ['瑞娜塔', 'renataglas'],
  Renekton: ['雷克顿', '鳄鱼', 'renekton'],
  Rengar: ['雷恩加尔', '狮子狗', 'rengar'],
  Riven: ['锐雯', 'riven', '瑞文'],
  Rumble: ['兰博', 'rumble'],
  Ryze: ['瑞兹', 'ryze', '流浪'],
  Samira: ['萨弥拉', 'samira'],
  Sejuani: ['瑟庄妮', '猪妹', 'sejuani'],
  Senna: ['赛娜', 'senna'],
  Seraphine: ['萨勒芬妮', 'seraphine'],
  Sett: ['瑟提', 'sett', '腕豪'],
  Shaco: ['萨科', '小丑', 'shaco'],
  Shen: ['慎', 'shen'],
  Shyvana: ['希瓦娜', '龙女', 'shyvana'],
  Singed: ['辛吉德', '炼金', 'singed'],
  Sion: ['赛恩', 'sion'],
  Sivir: ['希维尔', '轮子妈', 'sivir'],
  Skarner: ['斯卡纳', '蝎子', 'skarner'],
  Sona: ['娑娜', '琴女', 'sona'],
  Soraka: ['索拉卡', '星妈', 'soraka'],
  Swain: ['斯维因', '乌鸦', 'swain'],
  Sylas: ['塞拉斯', 'sylas'],
  Syndra: ['辛德拉', 'syndra'],
  TahmKench: ['塔姆', '蛤蟆', 'tahmkench', 'kench'],
  Taliyah: ['塔莉垭', '岩雀', 'taliyah'],
  Talon: ['泰隆', '男刀', 'talon'],
  Taric: ['塔里克', '宝石', 'taric'],
  Teemo: ['提莫', '提莫队长', 'teemo', '蘑菇'],
  Thresh: ['锤石', 'thresh'],
  Tristana: ['崔丝塔娜', '小炮', 'tristana'],
  Trundle: ['特朗德尔', '巨魔', 'trundle'],
  Tryndamere: ['泰达米尔', '蛮王', 'tryndamere', '蛮子'],
  TwistedFate: ['崔斯特', '卡牌', 'twistedfate', 'tf'],
  Twitch: ['图奇', '老鼠', 'twitch'],
  Udyr: ['乌迪尔', 'udyr'],
  Urgot: ['厄加特', 'urgot', '螃蟹'],
  Varus: ['韦鲁斯', 'varus'],
  Vayne: ['薇恩', 'vayne', 'vn'],
  Veigar: ['维迦', '小法', 'veigar'],
  Velkoz: ['维克兹', '大眼', 'velkoz'],
  Vex: ['薇古丝', 'vex'],
  Vi: ['蔚', 'vi'],
  Viego: ['佛耶戈', 'viego', '破败之王'],
  Viktor: ['维克托', 'viktor'],
  Vladimir: ['弗拉基米尔', '吸血鬼', 'vladimir', '吸血鬼'],
  Volibear: ['沃利贝尔', '狗熊', 'volibear'],
  Warwick: ['沃里克', '狼人', 'warwick', 'ww'],
  Xayah: ['霞', 'xayah'],
  Xerath: ['泽拉斯', 'xerath'],
  XinZhao: ['赵信', 'xinzhao', '赵信'],
  Yasuo: ['亚索', 'yasuo', '快乐风男', '疾风剑豪'],
  Yone: ['永恩', 'yone'],
  Yorick: ['约里克', '掘墓', 'yorick'],
  Yuumi: ['悠米', '猫咪', 'yuumi'],
  Zac: ['扎克', 'zac'],
  Zed: ['劫', 'zed'],
  Zeri: ['泽丽', 'zeri'],
  Ziggs: ['吉格斯', '炸弹人', 'ziggs'],
  Zilean: ['基兰', '时光', 'zilean'],
  Zoe: ['佐伊', 'zoe'],
  Zyra: ['婕拉', 'zyra'],
  Mel: ['梅尔', 'mel'],
  Ambessa: ['安蓓萨', 'ambessa'],
  Yunara: ['尤娜拉', 'yunara'],
  Locke: ['洛克', 'locke']
}

/**
 * 给定 DDragon 英雄 id（英文）和已知的 name/title，返回该英雄所有可搜索词。
 */
export function getChampionSearchTerms(
  championId: string,
  name: string,
  title: string
): string[] {
  const terms = new Set<string>()
  if (championId) terms.add(championId.toLowerCase())
  if (name) terms.add(name.toLowerCase())
  if (title) terms.add(title.toLowerCase())
  for (const alias of CHAMPION_ALIASES[championId] ?? []) {
    terms.add(alias.toLowerCase())
  }
  return [...terms]
}
