export const IPC_CHANNELS = {
  PING: 'app:ping',
  LCU_STATUS: 'lcu:status',
  LCU_GET_STATUS: 'lcu:get-status',
  LCU_GAME_PHASE: 'lcu:game-phase',
  MATCH_TEAM_PLAYERS: 'match:team-players',
  MATCH_PLAYER_HISTORY: 'match:player-history',
  MATCH_SEARCH: 'match:search',
  MATCH_GET_DETAIL: 'match:get-detail',
  GAME_LIVE_PLAYERS: 'game:live-players',
  TIER_GET_LIST: 'tier:get-list',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET_LOL_PATH: 'settings:set-lol-path',
  SETTINGS_SET_HOTKEY: 'settings:set-hotkey',
  TEAM_DATA_UPDATE: 'team:data-update',
  CHAMPION_DATA_GET: 'champion:data-get',
  CHAMPION_COUNTER_PICKS: 'champion:counter-picks',
  CHAMPION_SEARCH_INDEX: 'champion:search-index',
  CLIENT_STATUS_SET: 'client:status-set',
  CLIENT_STATUS_GET: 'client:status-get',
  CHAMP_SELECT_SESSION: 'champ-select:session',
  CHAMP_SELECT_UPDATE: 'champ-select:update',
  SPELL_PENDING_ADD: 'spell:pending-add',
  SPELL_PENDING_LIST: 'spell:pending-list',
  SPELL_PENDING_CONSUME: 'spell:pending-consume',
  SPELL_PENDING_DISMISS: 'spell:pending-dismiss'
} as const

export type IpcInvokeChannel =
  | typeof IPC_CHANNELS.PING
  | typeof IPC_CHANNELS.LCU_GET_STATUS
  | typeof IPC_CHANNELS.MATCH_TEAM_PLAYERS
  | typeof IPC_CHANNELS.MATCH_PLAYER_HISTORY
  | typeof IPC_CHANNELS.MATCH_SEARCH
  | typeof IPC_CHANNELS.MATCH_GET_DETAIL
  | typeof IPC_CHANNELS.TIER_GET_LIST
  | typeof IPC_CHANNELS.CHAMPION_DATA_GET
  | typeof IPC_CHANNELS.CHAMPION_COUNTER_PICKS
  | typeof IPC_CHANNELS.CHAMPION_SEARCH_INDEX
  | typeof IPC_CHANNELS.CLIENT_STATUS_SET
  | typeof IPC_CHANNELS.CLIENT_STATUS_GET
  | typeof IPC_CHANNELS.CHAMP_SELECT_SESSION
  | typeof IPC_CHANNELS.SETTINGS_GET
  | typeof IPC_CHANNELS.SETTINGS_SET_LOL_PATH
  | typeof IPC_CHANNELS.SETTINGS_SET_HOTKEY
  | typeof IPC_CHANNELS.SPELL_PENDING_LIST
  | typeof IPC_CHANNELS.SPELL_PENDING_CONSUME
  | typeof IPC_CHANNELS.SPELL_PENDING_DISMISS

export type IpcEventChannel =
  | typeof IPC_CHANNELS.LCU_STATUS
  | typeof IPC_CHANNELS.LCU_GAME_PHASE
  | typeof IPC_CHANNELS.GAME_LIVE_PLAYERS
  | typeof IPC_CHANNELS.TEAM_DATA_UPDATE
  | typeof IPC_CHANNELS.CHAMP_SELECT_UPDATE
  | typeof IPC_CHANNELS.SPELL_PENDING_ADD

export type IpcChannel = IpcInvokeChannel | IpcEventChannel

export const ALLOWED_INVOKE_CHANNELS: readonly IpcInvokeChannel[] = [
  IPC_CHANNELS.PING,
  IPC_CHANNELS.LCU_GET_STATUS,
  IPC_CHANNELS.MATCH_TEAM_PLAYERS,
  IPC_CHANNELS.MATCH_PLAYER_HISTORY,
  IPC_CHANNELS.MATCH_SEARCH,
  IPC_CHANNELS.MATCH_GET_DETAIL,
  IPC_CHANNELS.TIER_GET_LIST,
  IPC_CHANNELS.CHAMPION_DATA_GET,
  IPC_CHANNELS.CHAMPION_COUNTER_PICKS,
  IPC_CHANNELS.CHAMPION_SEARCH_INDEX,
  IPC_CHANNELS.CLIENT_STATUS_SET,
  IPC_CHANNELS.CLIENT_STATUS_GET,
  IPC_CHANNELS.CHAMP_SELECT_SESSION,
  IPC_CHANNELS.SETTINGS_GET,
  IPC_CHANNELS.SETTINGS_SET_LOL_PATH,
  IPC_CHANNELS.SETTINGS_SET_HOTKEY,
  IPC_CHANNELS.SPELL_PENDING_LIST,
  IPC_CHANNELS.SPELL_PENDING_CONSUME,
  IPC_CHANNELS.SPELL_PENDING_DISMISS
]

export const ALLOWED_EVENT_CHANNELS: readonly IpcEventChannel[] = [
  IPC_CHANNELS.LCU_STATUS,
  IPC_CHANNELS.LCU_GAME_PHASE,
  IPC_CHANNELS.GAME_LIVE_PLAYERS,
  IPC_CHANNELS.TEAM_DATA_UPDATE,
  IPC_CHANNELS.CHAMP_SELECT_UPDATE,
  IPC_CHANNELS.SPELL_PENDING_ADD
]

export const ALLOWED_IPC_CHANNELS: readonly IpcChannel[] = [
  ...ALLOWED_INVOKE_CHANNELS,
  ...ALLOWED_EVENT_CHANNELS
]
